#!/bin/bash

echo "================================"
echo "ChatGPT 翻译 API 抓包工具"
echo "================================"
echo ""
echo "由于 ChatGPT 网站有访问限制,我们需要通过浏览器手动分析 API。"
echo ""
echo "请按以下步骤操作:"
echo ""
echo "步骤 1: 打开 Chrome 或 Safari 浏览器"
echo "步骤 2: 按 Cmd+Option+I 打开开发者工具"
echo "步骤 3: 切换到 'Network' (网络) 标签"
echo "步骤 4: 访问 https://chatgpt.com/zh-Hans-CN/translate/"
echo "步骤 5: 在页面中输入文本并点击翻译"
echo "步骤 6: 在 Network 标签中查找包含 'translate' 或 'conversation' 的请求"
echo "步骤 7: 右键点击该请求,选择 'Copy' -> 'Copy as cURL'"
echo ""
echo "然后将复制的 cURL 命令保存到文件:"
echo "  nano /Users/ffff/Desktop/ChatGpt翻译/api_curl.txt"
echo ""
echo "================================"
echo ""
echo "常见的 ChatGPT API 端点:"
echo "  - https://chatgpt.com/backend-api/conversation"
echo "  - https://chatgpt.com/backend-api/translate"
echo "  - https://chat.openai.com/backend-api/conversation"
echo ""
echo "需要注意的请求头:"
echo "  - Authorization: Bearer ..."
echo "  - Cookie: ..."
echo "  - Content-Type: application/json"
echo ""
