#!/bin/bash

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

echo "================================"
echo "ChatGPT translation API packet capture tool"
echo "================================"
echo ""
echo "Due to access restrictions on the ChatGPT website, we need to manually analyze the API through the browser."
echo ""
echo "Please follow the steps below:"
echo ""
echo "Step 1: Open Chrome or Safari browser"
echo "Step 2: Press Cmd+Option+I to open developer tools"
echo "Step 3: Switch to 'Network' (Network) tab"
echo "Step 4: Visit https://chatgpt.com/zh-Hans-CN/translate/"
echo "Step 5: Enter text in the page and click Translate"
echo "Step 6: Look for requests containing 'translate' or 'conversation' in the Network tab"
echo "Step 7: Right click on the request and select 'Copy' -> 'Copy as cURL'"
echo ""
echo "Then save the copied cURL command to a file:"
echo "  nano ${PROJECT_DIR}/api_curl.txt"
echo ""
echo "================================"
echo ""
echo "Common ChatGPT API endpoints:"
echo "  - https://chatgpt.com/backend-api/conversation"
echo "  - https://chatgpt.com/backend-api/translate"
echo "  - https://chat.openai.com/backend-api/conversation"
echo ""
echo "Request headers that need attention:"
echo "  - Authorization: Bearer ..."
echo "  - Cookie: ..."
echo "  - Content-Type: application/json"
echo ""
